version: 1

formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  file:
    class: logging.FileHandler
    formatter: simple
    filename: logs/app.log

root:
  level: INFO
  handlers: [file]

disable_existing_loggers: False
